name: Verify dependency methods

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Package and deploy
        run: |
          pip install -U pip
          ./dev-install.sh
          tox

          
